/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolsPoolIdRouteImport } from './routes/pools.$poolId'
import { Route as PoolsPoolIdSettingsRouteImport } from './routes/pools.$poolId_.settings'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdRoute = PoolsPoolIdRouteImport.update({
  id: '/pools/$poolId',
  path: '/pools/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdSettingsRoute = PoolsPoolIdSettingsRouteImport.update({
  id: '/pools/$poolId_/settings',
  path: '/pools/$poolId/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/rules': typeof RulesRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools/$poolId/settings': typeof PoolsPoolIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/rules': typeof RulesRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools/$poolId/settings': typeof PoolsPoolIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/rules': typeof RulesRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools/$poolId_/settings': typeof PoolsPoolIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/rules'
    | '/pools/$poolId'
    | '/pools/$poolId/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/friends' | '/rules' | '/pools/$poolId' | '/pools/$poolId/settings'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/rules'
    | '/pools/$poolId'
    | '/pools/$poolId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  RulesRoute: typeof RulesRoute
  PoolsPoolIdRoute: typeof PoolsPoolIdRoute
  PoolsPoolIdSettingsRoute: typeof PoolsPoolIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId': {
      id: '/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/pools/$poolId'
      preLoaderRoute: typeof PoolsPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId_/settings': {
      id: '/pools/$poolId_/settings'
      path: '/pools/$poolId/settings'
      fullPath: '/pools/$poolId/settings'
      preLoaderRoute: typeof PoolsPoolIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  RulesRoute: RulesRoute,
  PoolsPoolIdRoute: PoolsPoolIdRoute,
  PoolsPoolIdSettingsRoute: PoolsPoolIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
